import torch
import torch.nn as nn

class HamiltonianNeuralNetwork(nn.Module):
    """
    Phase 3: The Physics-AI Convergence - Hamiltonian Neural Networks (HNNs)
    
    A standard PINN uses soft constraints (loss penalties) to approximate physics. 
    An HNN enforces physics BY CONSTRUCTION. 
    
    Instead of learning the vector field directly (q_dot, p_dot) = f(q, p), 
    we learn the scalar Hamiltonian (Total Energy) H(q, p). 
    
    The equations of motion are analytically derived via Autograd:
    q_dot =  ∂H / ∂p
    p_dot = -∂H / ∂q
    
    This guarantees that the learned dynamics are conservative and respect 
    Liouville's theorem (phase space volume preservation), solving the 
    long-term divergence problem inherent in standard neural networks.
    """
    def __init__(self, input_dim=2, hidden_dim=64):
        super().__init__()
        # The network takes phase space (q, p) and outputs a single scalar: Energy (H)
        self.hamiltonian = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.Tanh(), # Tanh for smooth higher-order derivatives
            nn.Linear(hidden_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, 1)
        )

    def forward(self, x):
        """
        x is the state vector [q, p]
        Returns the scalar Hamiltonian (Energy)
        """
        return self.hamiltonian(x)

    def time_derivative(self, x):
        """
        Computes the time derivatives (q_dot, p_dot) strictly via Hamilton's equations.
        Requires x to have requires_grad=True
        """
        # Ensure we can compute gradients with respect to input
        x = x.requires_grad_(True)
        
        # Forward pass to get Energy H
        H = self.forward(x)
        
        # Compute gradient ∂H/∂x = [∂H/∂q, ∂H/∂p]
        dH_dx = torch.autograd.grad(
            H.sum(), x, create_graph=True, retain_graph=True
        )[0]
        
        # Symplectic matrix J for a 1-DOF system (dim=2)
        # J = [[0, 1], [-1, 0]]
        # [q_dot, p_dot]^T = J * [∂H/∂q, ∂H/∂p]^T
        
        # For N-DOF, we generalize the symplectic split:
        dof = x.shape[1] // 2
        dH_dq = dH_dx[:, :dof]
        dH_dp = dH_dx[:, dof:]
        
        # q_dot = ∂H/∂p,  p_dot = -∂H/∂q
        return torch.cat([dH_dp, -dH_dq], dim=1)

    def loss_function(self, x, x_dot_true):
        """
        Loss is calculated against the TRUE time derivatives (from telemetry or simulator),
        but the network's prediction is forced to pass through the Hamiltonian bottleneck.
        """
        x_dot_pred = self.time_derivative(x)
        return nn.MSELoss()(x_dot_pred, x_dot_true)

if __name__ == "__main__":
    # ---------------------------------------------------------
    # Smoke Test: Ideal Pendulum
    # ---------------------------------------------------------
    print("--- Cyber-Physical HNN Initialized ---")
    
    # Generate dummy phase space data: q (angle), p (momentum)
    batch_size = 100
    q = torch.randn(batch_size, 1)
    p = torch.randn(batch_size, 1)
    x = torch.cat([q, p], dim=1)
    
    # Ideal Physics for a simple harmonic oscillator (H = p^2/2 + q^2/2)
    # True derivatives: q_dot = p, p_dot = -q
    q_dot_true = p
    p_dot_true = -q
    x_dot_true = torch.cat([q_dot_true, p_dot_true], dim=1)
    
    # Initialize Model
    hnn = HamiltonianNeuralNetwork(input_dim=2)
    
    # Compute Loss
    loss = hnn.loss_function(x, x_dot_true)
    print(f"Initial Symplectic Loss: {loss.item():.6f}")
    print("Notice: By definition, any vector field generated by this network is conservative.")
